# Automatically run terraform apply when a pull request is merged
when_modified:
  autoapply: true

# Use environment variables for GCP authentication
workflows:
  - tag_query: ""
    plan:
      - type: oidc
        provider: gcp
        service_account: "terrateam-state@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
        workload_identity_provider: "projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      - type: init
      - type: plan
    apply:
      - type: oidc
        provider: gcp
        service_account: "terrateam-state@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
        workload_identity_provider: "projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      - type: init
      - type: apply
