# Automatically run terraform apply when a pull request is merged
when_modified:
  autoapply: true

# Configure Google Cloud Storage for state backend
workflows:
  - tag_query: ""
    plan:
      - type: credentials
        provider: gcp
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - type: init
      - type: plan
    apply:
      - type: credentials
        provider: gcp
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - type: init
      - type: apply
