# Automatically run terraform apply when a pull request is merged
when_modified:
  autoapply: true

# Use environment variables for GCP authentication
workflows:
  - tag_query: ""
    plan:
      - type: env
        name: GOOGLE_CREDENTIALS
        cmd: ["echo", "${{ secrets.GCP_CREDENTIALS }}"]
        sensitive: true
      - type: init
      - type: plan
    apply:
      - type: env
        name: GOOGLE_CREDENTIALS
        cmd: ["echo", "${{ secrets.GCP_CREDENTIALS }}"]
        sensitive: true
      - type: init
      - type: apply
